# 1.Config/Import

In [1]:
import time
from datetime import datetime
import random
import os
import pickle
import itertools
import gc

# 데이터 분석 라이브러리
import numpy as np
import pandas as pd
import gzip
import zipfile
import math
from tqdm import tqdm
from tqdm import trange
tqdm.pandas()  # <- 이걸 실행해야 progress_apply가 활성화됨

# 케라스 라이브러리
import tensorflow as tf
from tensorflow.keras.layers import (
    Input, Embedding, Flatten, Dot, Multiply, Concatenate, Dropout, Dense, Add, Activation,
    MultiHeadAttention, Attention, Lambda, GlobalMaxPooling1D, GlobalAveragePooling1D
)
from tensorflow.keras.models import Model
import tensorflow.keras.backend as K
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam, SGD

# 데이터 분할, 인코더, 성능 평가 라이브러리
from sklearn.model_selection import train_test_split, ParameterGrid
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error
from sklearn.model_selection import ParameterGrid

print(f'pandas version: {pd.__version__}')
print(f'numpy version: {np.__version__}')
print(f'tensorflow version: {tf.__version__}')       # 2.13.0 등

pandas version: 1.5.3
numpy version: 1.23.5
tensorflow version: 2.12.0

In [27]:
DATA_SAVE_PATH = 'C:/Users/Bigdata64/Desktop/MK/dataset'
# DATA_SAVE_PATH = '/content/drive/MyDrive/박민경_논문1/dataset/prep'
CATEGORY = 'yelp'
DATASET_NM = 'yelp'

# 변수 설정
dict_col_nm = {
   'amazon': {
        'USER_ID': 'userID',
        'ITEM_ID': 'itemID',
        'RATING_COL': 'rating',
        'REVIEW_COL': 'reviewtext'
      },
   'yelp': {
        'USER_ID': 'user_id',
        'ITEM_ID': 'rest_id',
        'RATING_COL': 'review_stars',
        'REVIEW_COL': 'review_text'
      }
}

# 평균 패딩 시퀀스 길이 할당
dict_mean_seq_len = {
    'book':118,
    'movie':44,
    'yelp':113,
    'office': 51
}

USER_COL = 'user'
ITEM_COL = 'item'
RATING_COL = 'rating'
# REVIEW_COL = dict_col_nm[DATASET_NM]['REVIEW_COL']

mean_seq_length = dict_mean_seq_len[CATEGORY]

print(f"{CATEGORY} average seq length: {mean_seq_length}")

train_path = f'{DATA_SAVE_PATH}/{CATEGORY}_train_dict.pkl'
test_path = f'{DATA_SAVE_PATH}/{CATEGORY}_test_dict.pkl'

yelp average seq length: 113

# 2.load data

In [ ]:
df_input = pd.read_pickle(f"{DATA_SAVE_PATH}/{CATEGORY}_raw_embedding.pkl")

print(df_input.shape)
df_input.head(3)

(472877, 7)

,user,item,rating,user_embedding_textrank,user_embedding_bart,item_embedding_textrank,item_embedding_bart
0,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,"[304, 42, 8, 3, 29, 370, 231, 2, 1, 536, 30, 9...","[-1.598509, -0.997596, 0.5327545, -1.525021, 1...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321..."
1,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,"[46, 898, 383, 71, 44, 14, 49, 8, 32, 19, 32, ...","[-1.4743725, -1.3923125, -0.2920361, -2.608637...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321..."
2,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,"[21, 52, 3, 190, 7, 14, 1, 121, 188, 919, 8, 3...","[-0.21176815, -0.2568603, -1.0278563, -2.40477...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321..."

## (1)grouping

In [4]:
# count interaction by user
df_user_counts = df_input.groupby("user")["rating"].count().rename("cnt").reset_index()      # ← DataFrame으로 변환됨


# give rank based on the num of  interaction per user
df_user_counts["pct"] = df_user_counts["cnt"].rank(method="first", pct=True)

# assign user group
df_user_counts["user_group"] = pd.cut(
    df_user_counts["pct"],
    bins=[0, 0.25, 0.5, 0.75, 1.0],
    labels=[1, 2, 3, 4],
    include_lowest=True
).astype(int)

df_user_counts.head(5)

                     user  cnt       pct  user_group
0  --4AjktZiHowEIBCMd4CZA   12  0.684666           3
1  --F7iEaFFPO1UYemj-dUNw    6  0.187627           1
2  --_r6E98SNIrGU7weyNxbw   32  0.920491           4
3  --ccVMj2PN6Z9qtdOdlung    6  0.187658           1
4  --dVKamoZnV2vYwKtWMVVA   14  0.743281           3

In [5]:
# mapping on dictionary
user_to_group = dict(zip(df_user_counts["user"], df_user_counts["user_group"]))

# mapping on df
df_input["user_group"] = df_input["user"].map(user_to_group)

df_input.head(5)

,user,item,rating,user_embedding_textrank,user_embedding_bart,item_embedding_textrank,item_embedding_bart,user_group
0,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,"[304, 42, 8, 3, 29, 370, 231, 2, 1, 536, 30, 9...","[-1.598509, -0.997596, 0.5327545, -1.525021, 1...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321...",4
1,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,"[46, 898, 383, 71, 44, 14, 49, 8, 32, 19, 32, ...","[-1.4743725, -1.3923125, -0.2920361, -2.608637...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321...",4
2,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,"[21, 52, 3, 190, 7, 14, 1, 121, 188, 919, 8, 3...","[-0.21176815, -0.2568603, -1.0278563, -2.40477...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321...",4
3,dCooFVCk8M1nVaQqcfTL3Q,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,"[39, 1, 470, 6, 642, 2, 2531, 2, 4, 429, 33, 4...","[0.82523656, 0.91178995, 0.60730594, -4.156382...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321...",2
4,gy7Ss1uTpCjbbGsghTvNsw,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,"[9, 3, 208, 119, 16, 22, 26, 19, 382, 17, 64, ...","[-2.3661036, -0.6385349, 0.5271855, -3.6942627...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321...",3

In [6]:
# split dataframe based on user group
df_g1 = df_input[df_input['user_group']==1]
df_g2 = df_input[df_input['user_group']==2]
df_g3 = df_input[df_input['user_group']==3]
df_g4 = df_input[df_input['user_group']==4]

print(
    f"user group1: {df_g1['user_group'].unique()}", 
    f"user group2: {df_g2['user_group'].unique()}", 
    f"user group3: {df_g3['user_group'].unique()}", 
    f"user group4: {df_g4['user_group'].unique()}", 
    )

user group1: [1] user group2: [2] user group3: [3] user group4: [4]

In [7]:
# save user group data
df_input.to_pickle(f"{DATA_SAVE_PATH}/df_{CATEGORY}_input.pkl")
print("✅ df_input.pkl 저장 완료")

✅ df_input.pkl 저장 완료

In [8]:
with open(f"{DATA_SAVE_PATH}/{CATEGORY}_user_to_group.pkl", "wb") as f:
    pickle.dump(user_to_group, f)

print(f"✅ {CATEGORY}_user_to_group.pkl 저장 완료")

✅ yelp_user_to_group.pkl 저장 완료

In [9]:
with open(f"{DATA_SAVE_PATH}/{CATEGORY}_user_to_group.pkl", "rb") as f:
    user_to_group = pickle.load(f)

## (2)import embedding matrix

In [10]:
# user/item 임베딩 행렬 불러오기
user_embedding_matrix = np.load(f'{DATA_SAVE_PATH}/{CATEGORY}_user_glove_dic.npy', allow_pickle=True)
item_embedding_matrix = np.load(f'{DATA_SAVE_PATH}/{CATEGORY}_item_glove_dic.npy', allow_pickle=True)

user_embedding_matrix.shape, item_embedding_matrix.shape

((50001, 300), (50001, 300))

In [11]:
df_input = pd.read_pickle(f"{DATA_SAVE_PATH}/df_{CATEGORY}_input.pkl")

In [21]:
print(df_input.shape)
df_input.head(5)

(472877, 8)

,user,item,rating,user_embedding_textrank,user_embedding_bart,item_embedding_textrank,item_embedding_bart,user_group
0,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,"[304, 42, 8, 3, 29, 370, 231, 2, 1, 536, 30, 9...","[-1.598509, -0.997596, 0.5327545, -1.525021, 1...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321...",4
1,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4.0,"[46, 898, 383, 71, 44, 14, 49, 8, 32, 19, 32, ...","[-1.4743725, -1.3923125, -0.2920361, -2.608637...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321...",4
2,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,"[21, 52, 3, 190, 7, 14, 1, 121, 188, 919, 8, 3...","[-0.21176815, -0.2568603, -1.0278563, -2.40477...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321...",4
3,dCooFVCk8M1nVaQqcfTL3Q,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,"[39, 1, 470, 6, 642, 2, 2531, 2, 4, 429, 33, 4...","[0.82523656, 0.91178995, 0.60730594, -4.156382...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321...",2
4,gy7Ss1uTpCjbbGsghTvNsw,XQfwVwDr-v0ZS3_CbbE5Xw,2.0,"[9, 3, 208, 119, 16, 22, 26, 19, 382, 17, 64, ...","[-2.3661036, -0.6385349, 0.5271855, -3.6942627...","[764, 1, 5411, 11, 1, 112, 2, 45, 158, 5, 6009...","[-1.1874152, -0.1713701, -0.9754306, -1.811321...",3

# 3.Model

## (0)NCF

In [16]:
def Modeling(user_num, item_num, output_dim):

    # Input
    user = Input(shape=(1,), dtype='int64')
    item = Input(shape=(1,), dtype='int64')

    # GMF
    # MF User Vector
    gmf_user = Embedding(user_num, output_dim, input_length=1,name='gmf_user')(user)
    gmf_user = Flatten()(gmf_user)

    # MF Item Vector
    gmf_item = Embedding(item_num, output_dim, input_length=1, name='gmf_item')(item)
    gmf_item = Flatten()(gmf_item)

    # MLP
    # MLP User Vector
    mlp_user = Embedding(user_num, output_dim, input_length=1, name='mlp_user')(user)
    mlp_user = Flatten()(mlp_user)

    # MLP Item Vector
    mlp_item = Embedding(item_num, output_dim, input_length=1,name='mlp_item')(item)
    mlp_item = Flatten()(mlp_item)

    # GMF Layer : Element-wise Product
    gmf_mul = Multiply()([gmf_user, gmf_item])

    # MLP Layer 1
    mlp_concat = Concatenate()([mlp_user, mlp_item])

    # MLP Lyaer 2
    dense1 = Dense(32, activation='relu')(mlp_concat)
    dense2 = Dense(16, activation='relu')(dense1)
    dense3 = Dense(8, activation='relu')(dense2)

    # NeuMF Layer
    neumf_concat = Concatenate()([gmf_mul, dense3])

    # Output Layer
    output_layer = Dense(1, name='output_layer')(neumf_concat)

    model = Model(inputs=[user, item], outputs=output_layer)
    return model

In [17]:
def run_ncf_all_groups(
    df_total, user_to_group, rating_col,
    output_dim=16, batch_size=128, epochs=100, lr=0.0001, seed=42, n_runs=10
):
    results = []

    # 전체 df에서 필요한 컬럼만
    df_total = df_total[['user', 'item', rating_col]].copy()
    df_total['user_group'] = df_total['user'].map(user_to_group)

    for g in [1, 2, 3, 4]:
        print(f"\n==============================")
        print(f"🎯 NCF | Group G{g}")
        print("==============================")

        # ============================
        # ✅ (1) 그룹 데이터 준비 — 1번만
        # ============================
        df_g = df_total[df_total['user_group'] == g].reset_index(drop=True)
        print(f"📊 interactions: {len(df_g)}")

        # Label Encoding (group당 1번)
        user_encoder = LabelEncoder()
        item_encoder = LabelEncoder()

        df_g['user_enc'] = user_encoder.fit_transform(df_g['user'])
        df_g['item_enc'] = item_encoder.fit_transform(df_g['item'])

        user_num = df_g['user_enc'].nunique()
        item_num = df_g['item_enc'].nunique()

        # train / test split (group당 1번)
        train_data, test_data = train_test_split(
            df_g,
            test_size=0.2,
            random_state=seed,
            shuffle=True
        )

        train_users = train_data[['user_enc']].values
        train_items = train_data[['item_enc']].values
        train_y = train_data[rating_col].values

        test_users = test_data[['user_enc']].values
        test_items = test_data[['item_enc']].values
        test_y = test_data[rating_col].values

        # ============================
        # ✅ (2) 모델 학습만 n번 반복
        # ============================
        for run in range(n_runs):
            print(f"\n🔁 Group G{g} | Run {run+1}/{n_runs}")

            # # run별 seed (초기화만 다르게)
            # seed_everything(seed + run)

            model = Modeling(
                user_num=user_num,
                item_num=item_num,
                output_dim=output_dim
            )

            sgd = SGD(learning_rate=lr)
            model.compile(
                optimizer=sgd,
                loss='MSE',
                metrics=['mse', 'mae']
            )

            early_stopping = EarlyStopping(
                monitor='val_loss',
                min_delta=0.001,
                patience=5,
                verbose=1,
                mode='min',
                restore_best_weights=True
            )

            # 학습
            model.fit(
                x=[train_users, train_items],
                y=train_y,
                validation_split=0.125,
                batch_size=batch_size,
                epochs=epochs,
                callbacks=[early_stopping],
                verbose=1
            )

            # 평가
            predictions = model.predict([test_users, test_items]).flatten()

            MAE = mean_absolute_error(test_y, predictions)
            MSE = mean_squared_error(test_y, predictions)
            RMSE = np.sqrt(MSE)
            MAPE = mean_absolute_percentage_error(test_y, predictions) * 100

            metrics = {
                'group': g,
                'run': run + 1,
                'MAE': MAE,
                'MSE': MSE,
                'RMSE': RMSE,
                'MAPE': MAPE,
                'num_users': user_num,
                'num_items': item_num,
                'num_interactions': len(df_g)
            }

            print("📊 Metrics:", metrics)
            results.append(metrics)

            # 그래프/메모리 정리
            tf.keras.backend.clear_session()

    return pd.DataFrame(results)

In [18]:
def save_results_to_csv(df_results, prefix="results"):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    filename = f"{prefix}_{timestamp}.csv"
    df_results.to_csv(filename, index=False, encoding="utf-8-sig")
    print(f"📁 Saved: {filename}")
    
    return filename

In [28]:
df_ncf_results = run_ncf_all_groups(
    df_total=df_input,          # 원본 df_total
    user_to_group=user_to_group,
    rating_col=RATING_COL,
    output_dim=16,
    batch_size=128,
    epochs=100,
    lr=0.0001, 
    n_runs=10
)

print(df_ncf_results)

==============================
🎯 NCF | Group G1
==============================
📊 interactions: 43209

🔁 Group G1 | Run 1/10
Epoch 1/100
237/237 [==============================] - 1s 2ms/step - loss: 15.8153 - mse: 15.8153 - mae: 3.7454 - val_loss: 15.0984 - val_mse: 15.0984 - val_mae: 3.6540
Epoch 2/100
237/237 [==============================] - 0s 1ms/step - loss: 13.9243 - mse: 13.9243 - mae: 3.4834 - val_loss: 13.1736 - val_mse: 13.1736 - val_mae: 3.3805
Epoch 3/100
237/237 [==============================] - 0s 1ms/step - loss: 11.9771 - mse: 11.9771 - mae: 3.1917 - val_loss: 11.1475 - val_mse: 11.1475 - val_mae: 3.0662
Epoch 4/100
237/237 [==============================] - 0s 1ms/step - loss: 9.9040 - mse: 9.9040 - mae: 2.8599 - val_loss: 8.9721 - val_mse: 8.9721 - val_mae: 2.7300
Epoch 5/100
237/237 [==============================] - 0s 1ms/step - loss: 7.6970 - mse: 7.6970 - mae: 2.5159 - val_loss: 6.6921 - val_mse: 6.6921 - val_mae: 2.3523
Epoch 6/100
237/237 [==============================] - 0s 1ms/step - loss: 5.4980 - mse: 5.4980 - mae: 2.1164 - val_loss: 4.5617 - val_mse: 4.5617 - val_mae: 1.9473
Epoch 7/100
237/237 [==============================] - 0s 2ms/step - loss: 3.6565 - mse: 3.6565 - mae: 1.7462 - val_loss: 2.9923 - val_mse: 2.9923 - val_mae: 1.5851
Epoch 8/100
237/237 [==============================] - 0s 1ms/step - loss: 2.5006 - mse: 2.5006 - mae: 1.4351 - val_loss: 2.1701 - val_mse: 2.1701 - val_mae: 1.3414
Epoch 9/100
237/237 [==============================] - 0s 1ms/step - loss: 1.9945 - mse: 1.9945 - mae: 1.2693 - val_loss: 1.8665 - val_mse: 1.8665 - val_mae: 1.2115
Epoch 10/100
237/237 [==============================] - 0s 1ms/step - loss: 1.8347 - mse: 1.8347 - mae: 1.1757 - val_loss: 1.7788 - val_mse: 1.7788 - val_mae: 1.1410
Epoch 11/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7949 - mse: 1.7949 - mae: 1.1277 - val_loss: 1.7557 - val_mse: 1.7557 - val_mae: 1.1065
Epoch 12/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7865 - mse: 1.7865 - mae: 1.1050 - val_loss: 1.7496 - val_mse: 1.7496 - val_mae: 1.0912
Epoch 13/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7848 - mse: 1.7848 - mae: 1.0945 - val_loss: 1.7478 - val_mse: 1.7478 - val_mae: 1.0849
Epoch 14/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7844 - mse: 1.7844 - mae: 1.0905 - val_loss: 1.7470 - val_mse: 1.7470 - val_mae: 1.0816
Epoch 15/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7843 - mse: 1.7843 - mae: 1.0885 - val_loss: 1.7467 - val_mse: 1.7467 - val_mae: 1.0801
Epoch 16/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7842 - mse: 1.7842 - mae: 1.0871 - val_loss: 1.7466 - val_mse: 1.7466 - val_mae: 1.0799
Epoch 17/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7841 - mse: 1.7841 - mae: 1.0871 - val_loss: 1.7466 - val_mse: 1.7466 - val_mae: 1.0798
Epoch 18/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7841 - mse: 1.7841 - mae: 1.0882 - val_loss: 1.7463 - val_mse: 1.7463 - val_mae: 1.0786
Epoch 19/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7840 - mse: 1.7840 - mae: 1.0859 - val_loss: 1.7465 - val_mse: 1.7465 - val_mae: 1.0794
Epoch 20/100
193/237 [=======================>......] - ETA: 0s - loss: 1.7822 - mse: 1.7822 - mae: 1.0883Restoring model weights from the end of the best epoch: 15.
237/237 [==============================] - 0s 1ms/step - loss: 1.7840 - mse: 1.7840 - mae: 1.0876 - val_loss: 1.7463 - val_mse: 1.7463 - val_mae: 1.0787
Epoch 20: early stopping
271/271 [==============================] - 0s 675us/step
📊 Metrics: {'group': 1, 'run': 1, 'MAE': 1.0803701445284444, 'MSE': 1.7641348850193794, 'RMSE': 1.3282073953337932, 'MAPE': 50.003405199193985, 'num_users': 8231, 'num_items': 5974, 'num_interactions': 43209}

🔁 Group G1 | Run 2/10
Epoch 1/100
237/237 [==============================] - 1s 2ms/step - loss: 15.8914 - mse: 15.8914 - mae: 3.7555 - val_loss: 15.2120 - val_mse: 15.2120 - val_mae: 3.6695
Epoch 2/100
237/237 [==============================] - 0s 1ms/step - loss: 14.0975 - mse: 14.0975 - mae: 3.5083 - val_loss: 13.4213 - val_mse: 13.4213 - val_mae: 3.4168
Epoch 3/100
237/237 [==============================] - 0s 1ms/step - loss: 12.3262 - mse: 12.3262 - mae: 3.2458 - val_loss: 11.6128 - val_mse: 11.6128 - val_mae: 3.1410
Epoch 4/100
237/237 [==============================] - 0s 1ms/step - loss: 10.4919 - mse: 10.4919 - mae: 2.9520 - val_loss: 9.6953 - val_mse: 9.6953 - val_mae: 2.8368
Epoch 5/100
237/237 [==============================] - 0s 1ms/step - loss: 8.5306 - mse: 8.5306 - mae: 2.6503 - val_loss: 7.6403 - val_mse: 7.6403 - val_mae: 2.5180
Epoch 6/100
237/237 [==============================] - 0s 1ms/step - loss: 6.4786 - mse: 6.4786 - mae: 2.3026 - val_loss: 5.5617 - val_mse: 5.5617 - val_mae: 2.1318
Epoch 7/100
237/237 [==============================] - 0s 1ms/step - loss: 4.5469 - mse: 4.5469 - mae: 1.9334 - val_loss: 3.7671 - val_mse: 3.7671 - val_mae: 1.7822
Epoch 8/100
237/237 [==============================] - 0s 1ms/step - loss: 3.0756 - mse: 3.0756 - mae: 1.6000 - val_loss: 2.5818 - val_mse: 2.5818 - val_mae: 1.4579
Epoch 9/100
237/237 [==============================] - 0s 1ms/step - loss: 2.2500 - mse: 2.2500 - mae: 1.3596 - val_loss: 2.0241 - val_mse: 2.0241 - val_mae: 1.2886
Epoch 10/100
237/237 [==============================] - 0s 1ms/step - loss: 1.9184 - mse: 1.9184 - mae: 1.2325 - val_loss: 1.8287 - val_mse: 1.8287 - val_mae: 1.1850
Epoch 11/100
237/237 [==============================] - 0s 1ms/step - loss: 1.8184 - mse: 1.8184 - mae: 1.1582 - val_loss: 1.7730 - val_mse: 1.7730 - val_mae: 1.1305
Epoch 12/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7935 - mse: 1.7935 - mae: 1.1214 - val_loss: 1.7572 - val_mse: 1.7572 - val_mae: 1.1029
Epoch 13/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7877 - mse: 1.7877 - mae: 1.1033 - val_loss: 1.7526 - val_mse: 1.7526 - val_mae: 1.0896
Epoch 14/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7865 - mse: 1.7865 - mae: 1.0940 - val_loss: 1.7512 - val_mse: 1.7512 - val_mae: 1.0841
Epoch 15/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7862 - mse: 1.7862 - mae: 1.0901 - val_loss: 1.7507 - val_mse: 1.7507 - val_mae: 1.0819
Epoch 16/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7861 - mse: 1.7861 - mae: 1.0889 - val_loss: 1.7504 - val_mse: 1.7504 - val_mae: 1.0804
Epoch 17/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7861 - mse: 1.7861 - mae: 1.0875 - val_loss: 1.7504 - val_mse: 1.7504 - val_mae: 1.0806
Epoch 18/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7860 - mse: 1.7860 - mae: 1.0874 - val_loss: 1.7504 - val_mse: 1.7504 - val_mae: 1.0810
Epoch 19/100
232/237 [============================>.] - ETA: 0s - loss: 1.7843 - mse: 1.7843 - mae: 1.0874Restoring model weights from the end of the best epoch: 14.
237/237 [==============================] - 0s 1ms/step - loss: 1.7860 - mse: 1.7860 - mae: 1.0877 - val_loss: 1.7505 - val_mse: 1.7505 - val_mae: 1.0813
Epoch 19: early stopping
271/271 [==============================] - 0s 715us/step
📊 Metrics: {'group': 1, 'run': 2, 'MAE': 1.0821406155983295, 'MSE': 1.7617310787992173, 'RMSE': 1.3273021806654344, 'MAPE': 49.931365490180426, 'num_users': 8231, 'num_items': 5974, 'num_interactions': 43209}

🔁 Group G1 | Run 3/10
Epoch 1/100
237/237 [==============================] - 1s 2ms/step - loss: 15.7688 - mse: 15.7688 - mae: 3.7389 - val_loss: 15.0020 - val_mse: 15.0020 - val_mae: 3.6408
Epoch 2/100
237/237 [==============================] - 0s 1ms/step - loss: 13.7353 - mse: 13.7353 - mae: 3.4561 - val_loss: 12.8510 - val_mse: 12.8510 - val_mae: 3.3323
Epoch 3/100
237/237 [==============================] - 0s 1ms/step - loss: 11.4748 - mse: 11.4748 - mae: 3.1107 - val_loss: 10.4174 - val_mse: 10.4174 - val_mae: 2.9446
Epoch 4/100
237/237 [==============================] - 0s 1ms/step - loss: 8.9153 - mse: 8.9153 - mae: 2.7078 - val_loss: 7.6794 - val_mse: 7.6794 - val_mae: 2.5248
Epoch 5/100
237/237 [==============================] - 0s 1ms/step - loss: 6.1813 - mse: 6.1813 - mae: 2.2450 - val_loss: 4.9635 - val_mse: 4.9635 - val_mae: 2.0222
Epoch 6/100
237/237 [==============================] - 0s 1ms/step - loss: 3.8256 - mse: 3.8256 - mae: 1.7816 - val_loss: 2.9905 - val_mse: 2.9905 - val_mae: 1.5846
Epoch 7/100
237/237 [==============================] - 0s 1ms/step - loss: 2.4419 - mse: 2.4419 - mae: 1.4171 - val_loss: 2.0868 - val_mse: 2.0868 - val_mae: 1.3127
Epoch 8/100
237/237 [==============================] - 0s 1ms/step - loss: 1.9346 - mse: 1.9346 - mae: 1.2391 - val_loss: 1.8234 - val_mse: 1.8234 - val_mae: 1.1816
Epoch 9/100
237/237 [==============================] - 0s 1ms/step - loss: 1.8123 - mse: 1.8123 - mae: 1.1509 - val_loss: 1.7658 - val_mse: 1.7658 - val_mae: 1.1219
Epoch 10/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7898 - mse: 1.7898 - mae: 1.1131 - val_loss: 1.7531 - val_mse: 1.7531 - val_mae: 1.0963
Epoch 11/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7859 - mse: 1.7859 - mae: 1.0978 - val_loss: 1.7497 - val_mse: 1.7497 - val_mae: 1.0852
Epoch 12/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7853 - mse: 1.7853 - mae: 1.0895 - val_loss: 1.7491 - val_mse: 1.7491 - val_mae: 1.0824
Epoch 13/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7852 - mse: 1.7852 - mae: 1.0886 - val_loss: 1.7486 - val_mse: 1.7486 - val_mae: 1.0805
Epoch 14/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7851 - mse: 1.7851 - mae: 1.0884 - val_loss: 1.7484 - val_mse: 1.7484 - val_mae: 1.0789
Epoch 15/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7851 - mse: 1.7851 - mae: 1.0866 - val_loss: 1.7483 - val_mse: 1.7483 - val_mae: 1.0789
Epoch 16/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7850 - mse: 1.7850 - mae: 1.0865 - val_loss: 1.7484 - val_mse: 1.7484 - val_mae: 1.0797
Epoch 17/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7850 - mse: 1.7850 - mae: 1.0871 - val_loss: 1.7483 - val_mse: 1.7483 - val_mae: 1.0792
Epoch 18/100
197/237 [=======================>......] - ETA: 0s - loss: 1.7850 - mse: 1.7850 - mae: 1.0877Restoring model weights from the end of the best epoch: 13.
237/237 [==============================] - 0s 1ms/step - loss: 1.7850 - mse: 1.7850 - mae: 1.0869 - val_loss: 1.7483 - val_mse: 1.7483 - val_mae: 1.0791
Epoch 18: early stopping
271/271 [==============================] - 0s 666us/step
📊 Metrics: {'group': 1, 'run': 3, 'MAE': 1.079039806322046, 'MSE': 1.7619299801197839, 'RMSE': 1.3273771054676904, 'MAPE': 49.97190531100386, 'num_users': 8231, 'num_items': 5974, 'num_interactions': 43209}

🔁 Group G1 | Run 4/10
Epoch 1/100
237/237 [==============================] - 1s 2ms/step - loss: 15.8794 - mse: 15.8794 - mae: 3.7536 - val_loss: 15.2127 - val_mse: 15.2127 - val_mae: 3.6696
Epoch 2/100
237/237 [==============================] - 0s 1ms/step - loss: 14.1191 - mse: 14.1191 - mae: 3.5116 - val_loss: 13.4729 - val_mse: 13.4729 - val_mae: 3.4244
Epoch 3/100
237/237 [==============================] - 0s 1ms/step - loss: 12.3992 - mse: 12.3992 - mae: 3.2571 - val_loss: 11.7211 - val_mse: 11.7211 - val_mae: 3.1583
Epoch 4/100
237/237 [==============================] - 0s 1ms/step - loss: 10.6295 - mse: 10.6295 - mae: 2.9743 - val_loss: 9.8811 - val_mse: 9.8811 - val_mae: 2.8635
Epoch 5/100
237/237 [==============================] - 0s 1ms/step - loss: 8.7598 - mse: 8.7598 - mae: 2.6858 - val_loss: 7.9334 - val_mse: 7.9334 - val_mae: 2.5665
Epoch 6/100
237/237 [==============================] - 0s 1ms/step - loss: 6.8163 - mse: 6.8163 - mae: 2.3644 - val_loss: 5.9600 - val_mse: 5.9600 - val_mae: 2.2127
Epoch 7/100
237/237 [==============================] - 0s 1ms/step - loss: 4.9529 - mse: 4.9529 - mae: 2.0119 - val_loss: 4.1856 - val_mse: 4.1856 - val_mae: 1.8723
Epoch 8/100
237/237 [==============================] - 0s 1ms/step - loss: 3.4357 - mse: 3.4357 - mae: 1.6955 - val_loss: 2.8942 - val_mse: 2.8942 - val_mae: 1.5559
Epoch 9/100
237/237 [==============================] - 0s 1ms/step - loss: 2.4722 - mse: 2.4722 - mae: 1.4258 - val_loss: 2.1842 - val_mse: 2.1842 - val_mae: 1.3467
Epoch 10/100
237/237 [==============================] - 0s 1ms/step - loss: 2.0147 - mse: 2.0147 - mae: 1.2783 - val_loss: 1.8900 - val_mse: 1.8900 - val_mae: 1.2261
Epoch 11/100
237/237 [==============================] - 0s 1ms/step - loss: 1.8495 - mse: 1.8495 - mae: 1.1885 - val_loss: 1.7910 - val_mse: 1.7910 - val_mae: 1.1547
Epoch 12/100
237/237 [==============================] - 0s 1ms/step - loss: 1.8008 - mse: 1.8008 - mae: 1.1377 - val_loss: 1.7609 - val_mse: 1.7609 - val_mae: 1.1167
Epoch 13/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7881 - mse: 1.7881 - mae: 1.1125 - val_loss: 1.7515 - val_mse: 1.7515 - val_mae: 1.0969
Epoch 14/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7851 - mse: 1.7851 - mae: 1.0984 - val_loss: 1.7487 - val_mse: 1.7487 - val_mae: 1.0881
Epoch 15/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7844 - mse: 1.7844 - mae: 1.0923 - val_loss: 1.7477 - val_mse: 1.7477 - val_mae: 1.0842
Epoch 16/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7842 - mse: 1.7842 - mae: 1.0899 - val_loss: 1.7471 - val_mse: 1.7471 - val_mae: 1.0813
Epoch 17/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7841 - mse: 1.7841 - mae: 1.0873 - val_loss: 1.7469 - val_mse: 1.7469 - val_mae: 1.0806
Epoch 18/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7841 - mse: 1.7841 - mae: 1.0873 - val_loss: 1.7468 - val_mse: 1.7468 - val_mae: 1.0801
Epoch 19/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7840 - mse: 1.7840 - mae: 1.0868 - val_loss: 1.7468 - val_mse: 1.7468 - val_mae: 1.0802
Epoch 20/100
237/237 [==============================] - 0s 1ms/step - loss: 1.7840 - mse: 1.7840 - mae: 1.0868 - val_loss: 1.7467 - val_mse: 1.7467 - val_mae: 1.0797
Epoch 21/100
231/237 [============================>.] - ETA: 0s - loss: 1.7834 - mse: 1.7834 - mae: 1.0867Restoring model weights from the end of the best epoch: 16.
237/237 [==============================] - 0s 1ms/step - loss: 1.7839 - mse: 1.7839 - mae: 1.0869 - val_loss: 1.7466 - val_mse: 1.7466 - val_mae: 1.0795
Epoch 21: early stopping
271/271 [==============================] - 0s 658us/step
📊 Metrics: {'group': 1, 'run': 4, 'MAE': 1.0797197200501027, 'MSE': 1.761472337358344, 'RMSE': 1.327204708158596, 'MAPE': 49.948371208938084, 'num_users': 8231, 'num_items': 5974, 'num_interactions': 43209}

🔁 Group G1 | Run 5/10
Epoch 1/100
237/237 [==============================] - 1s 2ms/step - loss: 16.1545 - mse: 16.1545 - mae: 3.7902 - val_loss: 15.6933 - val_mse: 15.6933 - val_mae: 3.7345
Epoch 2/100
237/237 [==============================] - 0s 1ms/step - loss: 14.8273 - mse: 14.8273 - mae: 3.6110 - val_loss: 14.4397 - val_mse: 14.4397 - val_mae: 3.5627
Epoch 3/100
237/237 [==============================] - 0s 1ms/step - loss: 13.6448 - mse: 13.6448 - mae: 3.4436 - val_loss: 13.3014 - val_mse: 13.3014 - val_mae: 3.3992
Epoch 4/100
237/237 [==============================] - 0s 1ms/step - loss: 12.5701 - mse: 12.5701 - mae: 3.2839 - val_loss: 12.2661 - val_mse: 12.2661 - val_mae: 3.2434
Epoch 5/100
237/237 [==============================] - 0s 1ms/step - loss: 11.5930 - mse: 11.5930 - mae: 3.1316 - val_loss: 11.3234 - val_mse: 11.3234 - val_mae: 3.0946
Epoch 6/100
237/237 [==============================] - 0s 1ms/step - loss: 10.7038 - mse: 10.7038 - mae: 2.9865 - val_loss: 10.4647 - val_mse: 10.4647 - val_mae: 2.9526
Epoch 7/100
237/237 [==============================] - 0s 1ms/step - loss: 9.8941 - mse: 9.8941 - mae: 2.8545 - val_loss: 9.6832 - val_mse: 9.6832 - val_mae: 2.8351
Epoch 8/100
237/237 [==============================] - 0s 1ms/step - loss: 9.1576 - mse: 9.1576 - mae: 2.7469 - val_loss: 8.9714 - val_mse: 8.9714 - val_mae: 2.7299
Epoch 9/100
237/237 [==============================] - 0s 1ms/step - loss: 8.4871 - mse: 8.4871 - mae: 2.6451 - val_loss: 8.3229 - val_mse: 8.3229 - val_mae: 2.6294
Epoch 10/100
237/237 [==============================] - 0s 1ms/step - loss: 7.8767 - mse: 7.8767 - mae: 2.5482 - val_loss: 7.7322 - val_mse: 7.7322 - val_mae: 2.5334
Epoch 11/100
237/237 [==============================] - 0s 1ms/step - loss: 7.3209 - mse: 7.3209 - mae: 2.4557 - val_loss: 7.1937 - val_mse: 7.1937 - val_mae: 2.4417
Epoch 12/100
237/237 [==============================] - 0s 1ms/step - loss: 6.8145 - mse: 6.8145 - mae: 2.3671 - val_loss: 6.7027 - val_mse: 6.7027 - val_mae: 2.3541
Epoch 13/100
237/237 [==============================] - 0s 1ms/step - loss: 6.3530 - mse: 6.3530 - mae: 2.2824 - val_loss: 6.2544 - val_mse: 6.2544 - val_mae: 2.2702
Epoch 14/100
237/237 [==============================] - 0s 1ms/step - loss: 5.9320 - mse: 5.9320 - mae: 2.2012 - val_loss: 5.8453 - val_mse: 5.8453 - val_mae: 2.1899
Epoch 15/100
237/237 [==============================] - 0s 1ms/step - loss: 5.5481 - mse: 5.5481 - mae: 2.1236 - val_loss: 5.4716 - val_mse: 5.4716 - val_mae: 2.1130
Epoch 16/100
237/237 [==============================] - 0s 1ms/step - loss: 5.1975 - mse: 5.1975 - mae: 2.0545 - val_loss: 5.1304 - val_mse: 5.1304 - val_mae: 2.0518
Epoch 17/100
237/237 [==============================] - 0s 1ms/step - loss: 4.8776 - mse: 4.8776 - mae: 1.9984 - val_loss: 4.8183 - val_mse: 4.8183 - val_mae: 1.9958
Epoch 18/100
237/237 [==============================] - 0s 1ms/step - loss: 4.5853 - mse: 4.5853 - mae: 1.9448 - val_loss: 4.5327 - val_mse: 4.5327 - val_mae: 1.9419
Epoch 19/100
237/237 [==============================] - 0s 1ms/step - loss: 4.3180 - mse: 4.3180 - mae: 1.8930 - val_loss: 4.2715 - val_mse: 4.2715 - val_mae: 1.8902
Epoch 20/100
237/237 [==============================] - 0s 1ms/step - loss: 4.0737 - mse: 4.0737 - mae: 1.8435 - val_loss: 4.0323 - val_mse: 4.0323 - val_mae: 1.8405
Epoch 21/100
237/237 [==============================] - 0s 1ms/step - loss: 3.8502 - mse: 3.8502 - mae: 1.7958 - val_loss: 3.8129 - val_mse: 3.8129 - val_mae: 1.7925
Epoch 22/100
237/237 [==============================] - 0s 1ms/step - loss: 3.6456 - mse: 3.6456 - mae: 1.7497 - val_loss: 3.6120 - val_mse: 3.6120 - val_mae: 1.7463
Epoch 23/100
237/237 [==============================] - 0s 1ms/step - loss: 3.4583 - mse: 3.4583 - mae: 1.7053 - val_loss: 3.4280 - val_mse: 3.4280 - val_mae: 1.7017
Epoch 24/100
237/237 [==============================] - 0s 1ms/step - loss: 3.2870 - mse: 3.2870 - mae: 1.6625 - val_loss: 3.2593 - val_mse: 3.2593 - val_mae: 1.6586
Epoch 25/100
237/237 [==============================] - 0s 1ms/step - loss: 3.1304 - mse: 3.1304 - mae: 1.6212 - val_loss: 3.1045 - val_mse: 3.1045 - val_mae: 1.6169
Epoch 26/100
237/237 [==============================] - 0s 1ms/step - loss: 2.9868 - mse: 2.9868 - mae: 1.5811 - val_loss: 2.9625 - val_mse: 2.9625 - val_mae: 1.5765
Epoch 27/100
237/237 [==============================] - 0s 1ms/step - loss: 2.8554 - mse: 2.8554 - mae: 1.5423 - val_loss: 2.8325 - val_mse: 2.8325 - val_mae: 1.5374
Epoch 28/100
237/237 [==============================] - 0s 1ms/step - loss: 2.7354 - mse: 2.7354 - mae: 1.5047 - val_loss: 2.7137 - val_mse: 2.7137 - val_mae: 1.4996
Epoch 29/100
237/237 [==============================] - 0s 1ms/step - loss: 2.6261 - mse: 2.6261 - mae: 1.4682 - val_loss: 2.6051 - val_mse: 2.6051 - val_mae: 1.4629
Epoch 30/100
237/237 [==============================] - 0s 1ms/step - loss: 2.5264 - mse: 2.5264 - mae: 1.4365 - val_loss: 2.5060 - val_mse: 2.5060 - val_mae: 1.4366
Epoch 31/100

In [29]:
save_results_to_csv(df_ncf_results, prefix=f"g1_g4_NCF_{CATEGORY}")

📁 Saved: g1_g4_NCF_yelp_20251218_1637.csv

'g1_g4_NCF_yelp_20251218_1637.csv'

## (1)Proposed Model

In [25]:
def point_wise_feed_forward_network(d_model, dff):
  return tf.keras.Sequential([
      tf.keras.layers.Dense(dff, activation='linear'),
      tf.keras.layers.Dense(d_model, activation='linear')
  ])

class CoAttentionBlock(tf.keras.layers.Layer):
    def __init__(self, num_heads, key_dim, dff, dropout_rate=0.1, epsilon=1e-6, input_dim=None, **kwargs):
        super(CoAttentionBlock, self).__init__(**kwargs)
        self.multi_head_attention = MultiHeadAttention(num_heads=num_heads, key_dim=key_dim, value_dim=key_dim)
        self.dropout = Dropout(dropout_rate)
        self.add = Add()
        self.layer_norm = tf.keras.layers.LayerNormalization(epsilon = epsilon)
        self.ffn = point_wise_feed_forward_network(input_dim, dff)
        self.flatten = Flatten()


    def call(self, inputs):
        text_expanded, image_expanded = inputs
        co_attention = self.multi_head_attention(text_expanded, image_expanded, image_expanded)
        co_attention = self.dropout(co_attention)
        co_attention = self.add([co_attention, text_expanded])
        co_attention = self.layer_norm(co_attention)

        co_attention_ffn = self.ffn(co_attention)
        co_attention_ffn = self.dropout(co_attention_ffn)
        co_attention_ffn = self.add([co_attention_ffn, co_attention])
        co_attention_ffn = self.layer_norm(co_attention_ffn)

        # return self.flatten(co_attention_ffn)
        return co_attention_ffn

class SelfAttentionBlock(tf.keras.layers.Layer):
    def __init__(self, num_heads, key_dim, dff, dropout_rate=0.1,  epsilon=1e-6, input_dim=None, **kwargs):
        super(SelfAttentionBlock, self).__init__(**kwargs)
        self.multi_head_attention = MultiHeadAttention(num_heads=num_heads, key_dim=key_dim, value_dim=key_dim)
        self.dropout = Dropout(dropout_rate)
        self.add = Add()
        self.layer_norm = tf.keras.layers.LayerNormalization(epsilon = epsilon)
        self.ffn = point_wise_feed_forward_network(input_dim, dff)
        self.flatten = Flatten()


    def call(self, inputs):
        information_expanded = inputs
        self_attention = self.multi_head_attention(information_expanded, information_expanded, information_expanded)
        self_attention = self.dropout(self_attention)
        self_attention = self.add([self_attention, information_expanded])
        self_attention = self.layer_norm(self_attention)

        self_attention_ffn = self.ffn(self_attention)
        self_attention_ffn = self.dropout(self_attention_ffn)
        self_attention_ffn = self.add([self_attention_ffn, self_attention])
        self_attention_ffn = self.layer_norm(self_attention_ffn)

        # return self.flatten(self_attention_ffn)
        return self_attention_ffn

In [26]:
def proposed_model(input_dim, textrank_bool = False, bart_bool = False,
                   textrank_user_embedding_matrix = None,
                   textrank_item_embedding_matrix = None,
                   output_dim = 300, num_heads = 4, dff = 1024,
                   fusion_version = 'gmu', gmu_activation = 'sigmoid',
                   mlp_depth=2, mlp_hidden_dim=128, dropout_rate = 0.2):
    """
    [input]
      - textrank_bool: textrank 요약을 반영하는지 여부
      - bart_bool: bart 요약을 반영하는지 여부
      - input_dim: 임베딩 층의 input_dim, 요약의 max_seq_length를 의미함          (※ 각 데이터셋의 평균 패딩 시퀀스 길이임)
      - output_dim: 각 textrank/bart 요약 임베딩 차원                          (=추출/추상형 요약 간 결합 전에 맞춰주어야 하는 차원의 크기)
      - fusion_version: 추출/추상형 요약 간의 결합 방식                           (ex. gmu, concat, inner-product)
      - gmu_activation: gmu로 결합할 때 활성화함수
      - mlp_hidden_dim: mlp 은닉층 차원
      - mlp_depth: mlp 은닉층 깊이
      - dropout_rate: dropout 비율

    [output]
      - model: 모델 객체
    """
    # 0. attn block
    key_dim = output_dim // num_heads

    self_attn_block = SelfAttentionBlock(
        num_heads=num_heads, key_dim=key_dim,
        dropout_rate=dropout_rate,
        dff=dff,
        input_dim=output_dim              # 여기서 input_dim으로 output_dim을 넘겨줘야 함
    )
    
    co_attn_block = CoAttentionBlock(
        num_heads=num_heads, key_dim=key_dim,
        dropout_rate=dropout_rate,
        dff=dff, input_dim=output_dim
    )

    if textrank_bool == True:
        user_textrank_input = Input(shape=(input_dim,), dtype='int32', name='user_textrank_input')
        item_textrank_input = Input(shape=(input_dim,), dtype='int32', name='item_textrank_input')

        # 1. user/item embedding & concat
        user_textrank_embedding = Embedding(
            input_dim = len(textrank_user_embedding_matrix),
            output_dim = 300, input_length = input_dim,
            weights = [textrank_user_embedding_matrix])(user_textrank_input)
        item_textrank_embedding = Embedding(
            input_dim = len(textrank_item_embedding_matrix),
            output_dim = 300, input_length = input_dim,
            weights = [textrank_item_embedding_matrix])(item_textrank_input)

        user_textrank_embedding = GlobalMaxPooling1D()(user_textrank_embedding)
        item_textrank_embedding = GlobalMaxPooling1D()(item_textrank_embedding)

        textrank_concat = Concatenate()([user_textrank_embedding, item_textrank_embedding])
        textrank_proj = Dense(output_dim, activation='linear')(textrank_concat)

        # 2. self multi-head attn
        textrank_input = self_attn_block(tf.expand_dims(textrank_proj, axis=1))      # (batch, 1, output_dim)
        textrank_input = tf.squeeze(textrank_input, axis=1)
    else:
        textrank_input = None

    if bart_bool == True:
        # 1. user/item embedding & concat
        user_bart_input = Input(shape=(768,), name='user_bart_input')
        item_bart_input = Input(shape=(768,), name='item_bart_input')

        bart_concat = Concatenate()([user_bart_input, item_bart_input])
        bart_proj = Dense(output_dim, activation='linear')(bart_concat)

        # 2. self multi-head attn
        bart_proj_expanded = tf.expand_dims(bart_proj, axis=1)                            # (batch, 1, output_dim)
        bart_input = self_attn_block(bart_proj_expanded)
        bart_input = tf.squeeze(bart_input, axis=1)
    else:
        bart_input = None


    # 3. Fusion
    if textrank_bool and bart_bool:
        ## 1) gmu: concat > gate > gated sum
        if fusion_version.lower() == 'gmu':
            concat_inputs = Concatenate(name='concat_inputs')([textrank_input, bart_input])
            gate_sum = Dense(output_dim, activation=gmu_activation, name='gmu_gate')(concat_inputs)

            tanh_textrank = Activation('tanh')(textrank_input)
            tanh_bart = Activation('tanh')(bart_input)

            gmu_output = Add()([
                  Multiply()([gate_sum, tanh_textrank]),
                  Multiply()([Lambda(lambda x: 1 - x)(gate_sum), tanh_bart])
              ])
            combined = gmu_output

        ## 2) concat
        elif fusion_version.lower() == 'concat':
            combined = Concatenate()([textrank_input, bart_input])

        ## 3) inner_product
        elif fusion_version.lower().startswith('inner'):
            combined = Dot(axes=-1)([textrank_input, bart_input])

        ## 4) element-wise
        elif fusion_version.lower().startswith('element'):
            combined = Multiply()([textrank_input, bart_input])
        
        ## 5) attn
        elif fusion_version.lower().startswith('at'):
            # co-attn 위해 다시 expand
            textrank_input_exp = tf.expand_dims(textrank_input, axis=1)  # shape: (None, 1, 300)
            bart_input_exp = tf.expand_dims(bart_input, axis=1)

            co_attn_tr = co_attn_block((textrank_input_exp, bart_input_exp))
            co_attn_br = co_attn_block((bart_input_exp, textrank_input_exp))
            combined = Concatenate(name = 'co_attn_output')([co_attn_tr, co_attn_br])
            combined = tf.squeeze(combined, axis=1)
            
        else:
            raise ValueError("Invalid version")

    elif textrank_bool:
        combined = textrank_input
    elif bart_bool:
        combined = bart_input
    else:
        raise ValueError("At least one of textrank_bool or bart_bool must be True.")


    # 4. MLP -> 평점 예측
    ## (combined의 차원이 'cag' 퓨전 시 2*output_dim이 될 수 있으므로, MLP가 이를 처리할 수 있도록 설계되었는지 확인해야 합니다.)
    mlp_hidden_units = [mlp_hidden_dim // (2 ** i) for i in range(mlp_depth)]
    x = combined
    for i, units in enumerate(mlp_hidden_units):
        x = Dense(units, activation='linear', name=f'mlp_dense_{i+1}')(x)
        if dropout_rate > 0:
            x = Dropout(dropout_rate, name=f'dropout_{i+1}')(x)
    rating_pred = Dense(1, activation='relu', name='rating_output')(x)


    # 5. 모델 구성
    input_list = []
    if textrank_bool == True:
        input_list += [user_textrank_input, item_textrank_input]
    if bart_bool == True:
        input_list += [user_bart_input, item_bart_input]

    model = Model(inputs=input_list, outputs=rating_pred, name=f'{fusion_version}_rating_model')

    return model

## (2)parameter

In [12]:
# 기본 고정값
default_params = {
    'learning_rate': 1e-4,
    'batch_size': 128,
    'dropout_rate': 0.2,
    'mlp_hidden_dim': 128,
    'mlp_depth': 2,
    'embedding_dim': 300,
    'input_dim': mean_seq_length,
    'fusion_version': 'gmu'
}

## (3)training

In [27]:
def run_experiment_once(
    user_embedding_matrix, item_embedding_matrix,
    train_inputs, train_y,
    test_inputs, test_y,
    default_params,
    fusion_version='gmu'
):
    """한 번의 모델 학습 + 평가를 수행하고 test_metrics를 반환"""

    model = proposed_model(
        textrank_bool=True, bart_bool=True,
        textrank_user_embedding_matrix=user_embedding_matrix,
        textrank_item_embedding_matrix=item_embedding_matrix,
        fusion_version=fusion_version,
        input_dim=default_params['input_dim'],
        output_dim=default_params['embedding_dim'],
        dropout_rate=default_params['dropout_rate'],
        mlp_hidden_dim=default_params['mlp_hidden_dim'],
        mlp_depth=default_params['mlp_depth']
    )

    model.compile(
        optimizer=Adam(learning_rate=default_params['learning_rate']),
        loss=tf.keras.losses.MeanSquaredError(),
        metrics=[tf.keras.metrics.MeanAbsoluteError(), tf.keras.metrics.MeanSquaredError()]
    )

    early_stopping = EarlyStopping(
        monitor='val_loss', mode='min', patience=5,
        restore_best_weights=True, verbose=0
    )

    history = model.fit(
        train_inputs,
        train_y,
        validation_split=0.125,
        epochs=100,
        batch_size=default_params['batch_size'],
        callbacks=[early_stopping],
        verbose=1
    )

    predicted = model.predict(test_inputs, verbose=0)

    test_metrics = {
        'MAE': mean_absolute_error(test_y, predicted),
        'MSE': mean_squared_error(test_y, predicted),
        'RMSE': np.sqrt(mean_squared_error(test_y, predicted)),
        'MAPE': 100 * mean_absolute_percentage_error(test_y, predicted)
    }

    return test_metrics

In [28]:
def run_experiment_n_times(
    n,
    user_embedding_matrix, item_embedding_matrix,
    train_inputs, train_y,
    test_inputs, test_y,
    default_params,
    fusion_version='gmu'
):
    results = []

    for i in range(n):
        print(f"🔄 Running experiment {i+1}/{n} ...")

        metrics = run_experiment_once(
            user_embedding_matrix, item_embedding_matrix,
            train_inputs, train_y,
            test_inputs, test_y,
            default_params,
            fusion_version=fusion_version
        )

        metrics['run'] = i + 1  # 몇 번째 실행인지 추가
        results.append(metrics)

    df_results = pd.DataFrame(results)
    
    return df_results

In [29]:
def run_group_experiment(
    group_num,
    df_input,
    user_to_group,
    user_embedding_matrix, item_embedding_matrix,
    default_params,
    n_runs=1   # 반복 횟수 지정 가능
):
    print(f"\n============================")
    print(f"🔍 Running Group G{group_num}")
    print("============================\n")

    # STEP 1: df_input에 group 태그 달기
    df_input['user_group'] = df_input['user'].map(user_to_group)

    # STEP 2: 선택한 그룹만 추출
    df_g = df_input[df_input['user_group'] == group_num].reset_index(drop=True)

    # STEP 3: train/test split
    df_train, df_test = train_test_split(
        df_g, test_size=0.2, random_state=42
    )

    # STEP 4: embedding 준비
    train_inputs = [
        np.vstack(df_train['user_embedding_textrank']),
        np.vstack(df_train['item_embedding_textrank']),
        np.vstack(df_train['user_embedding_bart']),
        np.vstack(df_train['item_embedding_bart']),
    ]
    train_y = df_train['rating'].values

    test_inputs = [
        np.vstack(df_test['user_embedding_textrank']),
        np.vstack(df_test['item_embedding_textrank']),
        np.vstack(df_test['user_embedding_bart']),
        np.vstack(df_test['item_embedding_bart']),
    ]
    test_y = df_test['rating'].values

    # STEP 5: 지정된 횟수(n_runs) 만큼 반복 실행
    group_results = []
    for run in range(n_runs):
        print(f"\n➡️  G{group_num} Run {run+1}/{n_runs}")
        metrics = run_experiment_once(
            user_embedding_matrix, item_embedding_matrix,
            train_inputs, train_y,
            test_inputs, test_y,
            default_params,
            fusion_version='gmu'
        )
        metrics['group'] = group_num
        metrics['run'] = run+1
        group_results.append(metrics)

    return group_results

In [30]:
def run_single_group_n_times(
    group_num,
    df_input,
    user_to_group,
    user_embedding_matrix,
    item_embedding_matrix,
    default_params,
    n_runs=5,
    test_size=0.2,
    random_state=42
):
    """
    특정 user group(G1~G4 중 하나)에 대해 n번 학습/평가 수행
    """
    print(f"\n==============================")
    print(f"🎯 Running Group G{group_num} for {n_runs} runs")
    print("==============================\n")

    # 1️⃣ group 태깅
    df = df_input.copy()
    df["user_group"] = df["user"].map(user_to_group)

    # 2️⃣ 특정 그룹만 필터링 (★ split 이전)
    df_g = df[df["user_group"] == group_num].reset_index(drop=True)

    print(f"📊 Group G{group_num} interactions: {len(df_g)}")

    # 3️⃣ train / test split
    df_train, df_test = train_test_split(
        df_g,
        test_size=test_size,
        random_state=random_state
    )

    # 4️⃣ X / y 생성 (컬럼명은 네 데이터에 맞게 수정!)
    train_inputs = [
        np.vstack(df_train["user_embedding_textrank"]),
        np.vstack(df_train["item_embedding_textrank"]),
        np.vstack(df_train["user_embedding_bart"]),
        np.vstack(df_train["item_embedding_bart"]),
    ]
    train_y = df_train["rating"].values

    test_inputs = [
        np.vstack(df_test["user_embedding_textrank"]),
        np.vstack(df_test["item_embedding_textrank"]),
        np.vstack(df_test["user_embedding_bart"]),
        np.vstack(df_test["item_embedding_bart"]),
    ]
    test_y = df_test["rating"].values

    # sanity check
    assert len(test_y) == test_inputs[0].shape[0], "❌ X/y length mismatch!"

    # 5️⃣ n번 반복 학습
    results = []

    for run in range(n_runs):
        print(f"\n🔁 G{group_num} | Run {run+1}/{n_runs}")

        metrics = run_experiment_once(
            user_embedding_matrix,
            item_embedding_matrix,
            train_inputs,
            train_y,
            test_inputs,
            test_y,
            default_params,
            fusion_version="gmu"
        )

        metrics["group"] = group_num
        metrics["run"] = run + 1
        results.append(metrics)

    return pd.DataFrame(results)

In [31]:
def run_all_groups(
    df_input,
    user_to_group,
    user_embedding_matrix, item_embedding_matrix,
    default_params,
    n_runs=1
):
    all_results = []

    for g in [1, 2, 3, 4]:
        group_res = run_group_experiment(
            g, df_input, user_to_group,
            user_embedding_matrix, item_embedding_matrix,
            default_params,
            n_runs=n_runs
        )
        all_results.extend(group_res)

    df_results = pd.DataFrame(all_results)
    return df_results

In [19]:
df_results = run_all_groups(
    df_input=df_input,
    user_to_group=user_to_group,   # 기존에 만든 dict
    user_embedding_matrix=user_embedding_matrix,
    item_embedding_matrix=item_embedding_matrix,
    default_params=default_params,
    n_runs=10   # 각 그룹을 몇 번 반복할지
)

print(df_results)

============================
🔍 Running Group G1
============================


➡️  G1 Run 1/10
Epoch 1/100
237/237 [==============================] - 56s 227ms/step - loss: 2.2425 - mean_absolute_error: 1.2024 - mean_squared_error: 2.2425 - val_loss: 1.6465 - val_mean_absolute_error: 1.0919 - val_mean_squared_error: 1.6465
Epoch 2/100
237/237 [==============================] - 52s 221ms/step - loss: 1.8081 - mean_absolute_error: 1.0934 - mean_squared_error: 1.8081 - val_loss: 1.7891 - val_mean_absolute_error: 0.9733 - val_mean_squared_error: 1.7891
Epoch 3/100
237/237 [==============================] - 52s 221ms/step - loss: 1.7052 - mean_absolute_error: 1.0566 - mean_squared_error: 1.7052 - val_loss: 1.6773 - val_mean_absolute_error: 0.9519 - val_mean_squared_error: 1.6773
Epoch 4/100
237/237 [==============================] - 52s 221ms/step - loss: 1.6901 - mean_absolute_error: 1.0509 - mean_squared_error: 1.6901 - val_loss: 1.4856 - val_mean_absolute_error: 0.9577 - val_mean_squared_error: 1.4856
Epoch 5/100
237/237 [==============================] - 52s 221ms/step - loss: 1.6215 - mean_absolute_error: 1.0283 - mean_squared_error: 1.6215 - val_loss: 1.6195 - val_mean_absolute_error: 0.9360 - val_mean_squared_error: 1.6195
Epoch 6/100
237/237 [==============================] - 53s 222ms/step - loss: 1.5742 - mean_absolute_error: 1.0098 - mean_squared_error: 1.5742 - val_loss: 1.4502 - val_mean_absolute_error: 0.9491 - val_mean_squared_error: 1.4502
Epoch 7/100
237/237 [==============================] - 52s 221ms/step - loss: 1.5186 - mean_absolute_error: 0.9890 - mean_squared_error: 1.5186 - val_loss: 1.5835 - val_mean_absolute_error: 0.9277 - val_mean_squared_error: 1.5835
Epoch 8/100
237/237 [==============================] - 53s 222ms/step - loss: 1.5140 - mean_absolute_error: 0.9860 - mean_squared_error: 1.5140 - val_loss: 1.4466 - val_mean_absolute_error: 0.9175 - val_mean_squared_error: 1.4466
Epoch 9/100
237/237 [==============================] - 53s 222ms/step - loss: 1.4772 - mean_absolute_error: 0.9714 - mean_squared_error: 1.4772 - val_loss: 1.4447 - val_mean_absolute_error: 0.9193 - val_mean_squared_error: 1.4447
Epoch 10/100
237/237 [==============================] - 53s 225ms/step - loss: 1.4589 - mean_absolute_error: 0.9636 - mean_squared_error: 1.4589 - val_loss: 1.5499 - val_mean_absolute_error: 0.9225 - val_mean_squared_error: 1.5499
Epoch 11/100
237/237 [==============================] - 53s 222ms/step - loss: 1.4036 - mean_absolute_error: 0.9427 - mean_squared_error: 1.4036 - val_loss: 1.4179 - val_mean_absolute_error: 0.9119 - val_mean_squared_error: 1.4179
Epoch 12/100
237/237 [==============================] - 53s 222ms/step - loss: 1.4060 - mean_absolute_error: 0.9428 - mean_squared_error: 1.4060 - val_loss: 1.5391 - val_mean_absolute_error: 0.9143 - val_mean_squared_error: 1.5391
Epoch 13/100
237/237 [==============================] - 53s 222ms/step - loss: 1.3517 - mean_absolute_error: 0.9227 - mean_squared_error: 1.3517 - val_loss: 1.4112 - val_mean_absolute_error: 0.9126 - val_mean_squared_error: 1.4112
Epoch 14/100
237/237 [==============================] - 53s 222ms/step - loss: 1.3240 - mean_absolute_error: 0.9120 - mean_squared_error: 1.3240 - val_loss: 1.6715 - val_mean_absolute_error: 0.9498 - val_mean_squared_error: 1.6715
Epoch 15/100
237/237 [==============================] - 53s 222ms/step - loss: 1.3035 - mean_absolute_error: 0.9030 - mean_squared_error: 1.3035 - val_loss: 1.4879 - val_mean_absolute_error: 0.9883 - val_mean_squared_error: 1.4879
Epoch 16/100
237/237 [==============================] - 53s 222ms/step - loss: 1.2832 - mean_absolute_error: 0.8925 - mean_squared_error: 1.2832 - val_loss: 1.4458 - val_mean_absolute_error: 0.9046 - val_mean_squared_error: 1.4458
Epoch 17/100
237/237 [==============================] - 53s 222ms/step - loss: 1.2371 - mean_absolute_error: 0.8773 - mean_squared_error: 1.2371 - val_loss: 1.4582 - val_mean_absolute_error: 0.9147 - val_mean_squared_error: 1.4582
Epoch 18/100
237/237 [==============================] - 53s 222ms/step - loss: 1.2188 - mean_absolute_error: 0.8677 - mean_squared_error: 1.2188 - val_loss: 1.7178 - val_mean_absolute_error: 0.9588 - val_mean_squared_error: 1.7178

➡️  G1 Run 2/10
Epoch 1/100
237/237 [==============================] - 56s 225ms/step - loss: 2.1908 - mean_absolute_error: 1.1909 - mean_squared_error: 2.1908 - val_loss: 1.6512 - val_mean_absolute_error: 0.9784 - val_mean_squared_error: 1.6512
Epoch 2/100
237/237 [==============================] - 53s 223ms/step - loss: 1.8444 - mean_absolute_error: 1.1013 - mean_squared_error: 1.8444 - val_loss: 1.5756 - val_mean_absolute_error: 0.9667 - val_mean_squared_error: 1.5756
Epoch 3/100
237/237 [==============================] - 53s 223ms/step - loss: 1.7345 - mean_absolute_error: 1.0668 - mean_squared_error: 1.7345 - val_loss: 1.5006 - val_mean_absolute_error: 0.9767 - val_mean_squared_error: 1.5006
Epoch 4/100
237/237 [==============================] - 53s 224ms/step - loss: 1.6742 - mean_absolute_error: 1.0470 - mean_squared_error: 1.6742 - val_loss: 1.4787 - val_mean_absolute_error: 0.9586 - val_mean_squared_error: 1.4787
Epoch 5/100
237/237 [==============================] - 53s 223ms/step - loss: 1.6249 - mean_absolute_error: 1.0270 - mean_squared_error: 1.6249 - val_loss: 1.7458 - val_mean_absolute_error: 0.9600 - val_mean_squared_error: 1.7458
Epoch 6/100
237/237 [==============================] - 53s 223ms/step - loss: 1.5973 - mean_absolute_error: 1.0171 - mean_squared_error: 1.5973 - val_loss: 1.5247 - val_mean_absolute_error: 0.9351 - val_mean_squared_error: 1.5247
Epoch 7/100
237/237 [==============================] - 53s 223ms/step - loss: 1.5665 - mean_absolute_error: 1.0049 - mean_squared_error: 1.5665 - val_loss: 1.4413 - val_mean_absolute_error: 0.9278 - val_mean_squared_error: 1.4413
Epoch 8/100
237/237 [==============================] - 53s 223ms/step - loss: 1.5230 - mean_absolute_error: 0.9886 - mean_squared_error: 1.5230 - val_loss: 1.4509 - val_mean_absolute_error: 0.9241 - val_mean_squared_error: 1.4509
Epoch 9/100
237/237 [==============================] - 53s 222ms/step - loss: 1.4833 - mean_absolute_error: 0.9770 - mean_squared_error: 1.4833 - val_loss: 1.4612 - val_mean_absolute_error: 0.9162 - val_mean_squared_error: 1.4612
Epoch 10/100
237/237 [==============================] - 53s 222ms/step - loss: 1.4449 - mean_absolute_error: 0.9588 - mean_squared_error: 1.4449 - val_loss: 1.5606 - val_mean_absolute_error: 0.9178 - val_mean_squared_error: 1.5606
Epoch 11/100
237/237 [==============================] - 53s 223ms/step - loss: 1.4276 - mean_absolute_error: 0.9530 - mean_squared_error: 1.4276 - val_loss: 1.4452 - val_mean_absolute_error: 0.9110 - val_mean_squared_error: 1.4452
Epoch 12/100
237/237 [==============================] - 53s 222ms/step - loss: 1.3989 - mean_absolute_error: 0.9417 - mean_squared_error: 1.3989 - val_loss: 1.4441 - val_mean_absolute_error: 0.9134 - val_mean_squared_error: 1.4441

➡️  G1 Run 3/10
Epoch 1/100
237/237 [==============================] - 55s 224ms/step - loss: 2.2319 - mean_absolute_error: 1.2036 - mean_squared_error: 2.2319 - val_loss: 1.5577 - val_mean_absolute_error: 1.0084 - val_mean_squared_error: 1.5577
Epoch 2/100
237/237 [==============================] - 53s 222ms/step - loss: 1.8232 - mean_absolute_error: 1.0983 - mean_squared_error: 1.8232 - val_loss: 1.5240 - val_mean_absolute_error: 0.9804 - val_mean_squared_error: 1.5240
Epoch 3/100
237/237 [==============================] - 53s 223ms/step - loss: 1.7137 - mean_absolute_error: 1.0592 - mean_squared_error: 1.7137 - val_loss: 1.5678 - val_mean_absolute_error: 0.9567 - val_mean_squared_error: 1.5678
Epoch 4/100
237/237 [==============================] - 53s 222ms/step - loss: 1.6663 - mean_absolute_error: 1.0428 - mean_squared_error: 1.6663 - val_loss: 1.6087 - val_mean_absolute_error: 0.9480 - val_mean_squared_error: 1.6087
Epoch 5/100
237/237 [==============================] - 53s 223ms/step - loss: 1.6193 - mean_absolute_error: 1.0271 - mean_squared_error: 1.6193 - val_loss: 1.5095 - val_mean_absolute_error: 1.0211 - val_mean_squared_error: 1.5095
Epoch 6/100
237/237 [==============================] - 53s 222ms/step - loss: 1.6129 - mean_absolute_error: 1.0237 - mean_squared_error: 1.6129 - val_loss: 1.5422 - val_mean_absolute_error: 0.9276 - val_mean_squared_error: 1.5422
Epoch 7/100
237/237 [==============================] - 53s 222ms/step - loss: 1.5321 - mean_absolute_error: 0.9913 - mean_squared_error: 1.5321 - val_loss: 1.5494 - val_mean_absolute_error: 0.9278 - val_mean_squared_error: 1.5494
Epoch 8/100
237/237 [==============================] - 53s 222ms/step - loss: 1.4916 - mean_absolute_error: 0.9791 - mean_squared_error: 1.4916 - val_loss: 1.9597 - val_mean_absolute_error: 1.0246 - val_mean_squared_error: 1.9597
Epoch 9/100
237/237 [==============================] - 53s 223ms/step - loss: 1.4981 - mean_absolute_error: 0.9803 - mean_squared_error: 1.4981 - val_loss: 1.4929 - val_mean_absolute_error: 0.9138 - val_mean_squared_error: 1.4929
Epoch 10/100
237/237 [==============================] - 53s 223ms/step - loss: 1.4490 - mean_absolute_error: 0.9618 - mean_squared_error: 1.4490 - val_loss: 1.4197 - val_mean_absolute_error: 0.9160 - val_mean_squared_error: 1.4197
Epoch 11/100
237/237 [==============================] - 53s 222ms/step - loss: 1.4001 - mean_absolute_error: 0.9431 - mean_squared_error: 1.4001 - val_loss: 1.4787 - val_mean_absolute_error: 0.9150 - val_mean_squared_error: 1.4787
Epoch 12/100
237/237 [==============================] - 53s 223ms/step - loss: 1.3924 - mean_absolute_error: 0.9420 - mean_squared_error: 1.3924 - val_loss: 1.6210 - val_mean_absolute_error: 0.9352 - val_mean_squared_error: 1.6210
Epoch 13/100
237/237 [==============================] - 53s 222ms/step - loss: 1.3630 - mean_absolute_error: 0.9278 - mean_squared_error: 1.3630 - val_loss: 1.4394 - val_mean_absolute_error: 0.9046 - val_mean_squared_error: 1.4394
Epoch 14/100
237/237 [==============================] - 53s 222ms/step - loss: 1.3503 - mean_absolute_error: 0.9223 - mean_squared_error: 1.3503 - val_loss: 1.4730 - val_mean_absolute_error: 0.9135 - val_mean_squared_error: 1.4730
Epoch 15/100
237/237 [==============================] - 53s 222ms/step - loss: 1.3163 - mean_absolute_error: 0.9093 - mean_squared_error: 1.3163 - val_loss: 1.7973 - val_mean_absolute_error: 0.9845 - val_mean_squared_error: 1.7973

➡️  G1 Run 4/10
Epoch 1/100
237/237 [==============================] - 55s 223ms/step - loss: 2.2474 - mean_absolute_error: 1.2056 - mean_squared_error: 2.2474 - val_loss: 1.6558 - val_mean_absolute_error: 0.9721 - val_mean_squared_error: 1.6558
Epoch 2/100
237/237 [==============================] - 52s 221ms/step - loss: 1.8242 - mean_absolute_error: 1.0971 - mean_squared_error: 1.8242 - val_loss: 1.6124 - val_mean_absolute_error: 0.9593 - val_mean_squared_error: 1.6124
Epoch 3/100
237/237 [==============================] - 52s 221ms/step - loss: 1.7353 - mean_absolute_error: 1.0661 - mean_squared_error: 1.7353 - val_loss: 1.4941 - val_mean_absolute_error: 0.9641 - val_mean_squared_error: 1.4941
Epoch 4/100
237/237 [==============================] - 52s 221ms/step - loss: 1.6699 - mean_absolute_error: 1.0441 - mean_squared_error: 1.6699 - val_loss: 1.5084 - val_mean_absolute_error: 0.9447 - val_mean_squared_error: 1.5084
Epoch 5/100
237/237 [==============================] - 52s 221ms/step - loss: 1.6160 - mean_absolute_error: 1.0237 - mean_squared_error: 1.6160 - val_loss: 1.6622 - val_mean_absolute_error: 0.9472 - val_mean_squared_error: 1.6622
Epoch 6/100
237/237 [==============================] - 52s 221ms/step - loss: 1.5872 - mean_absolute_error: 1.0124 - mean_squared_error: 1.5872 - val_loss: 1.4903 - val_mean_absolute_error: 0.9261 - val_mean_squared_error: 1.4903
Epoch 7/100
237/237 [==============================] - 52s 221ms/step - loss: 1.5631 - mean_absolute_error: 1.0026 - mean_squared_error: 1.5631 - val_loss: 1.4248 - val_mean_absolute_error: 0.9323 - val_mean_squared_error: 1.4248
Epoch 8/100
237/237 [==============================] - 52s 221ms/step - loss: 1.5175 - mean_absolute_error: 0.9886 - mean_squared_error: 1.5175 - val_loss: 1.4151 - val_mean_absolute_error: 0.9284 - val_mean_squared_error: 1.4151
Epoch 9/100
237/237 [==============================] - 52s 221ms/step - loss: 1.4821 - mean_absolute_error: 0.9734 - mean_squared_error: 1.4821 - val_loss: 1.8629 - val_mean_absolute_error: 0.9909 - val_mean_squared_error: 1.8629
Epoch 10/100
237/237 [==============================] - 52s 221ms/step - loss: 1.4506 - mean_absolute_error: 0.9608 - mean_squared_error: 1.4506 - val_loss: 1.4335 - val_mean_absolute_error: 0.9193 - val_mean_squared_error: 1.4335
Epoch 11/100
237/237 [==============================] - 52s 221ms/step - loss: 1.4309 - mean_absolute_error: 0.9537 - mean_squared_error: 1.4309 - val_loss: 1.8120 - val_mean_absolute_error: 0.9780 - val_mean_squared_error: 1.8120
Epoch 12/100
237/237 [==============================] - 52s 221ms/step - loss: 1.4090 - mean_absolute_error: 0.9467 - mean_squared_error: 1.4090 - val_loss: 1.5581 - val_mean_absolute_error: 0.9262 - val_mean_squared_error: 1.5581
Epoch 13/100
237/237 [==============================] - 52s 221ms/step - loss: 1.3695 - mean_absolute_error: 0.9312 - mean_squared_error: 1.3695 - val_loss: 1.3887 - val_mean_absolute_error: 0.9296 - val_mean_squared_error: 1.3887
Epoch 14/100
237/237 [==============================] - 52s 221ms/step - loss: 1.3410 - mean_absolute_error: 0.9201 - mean_squared_error: 1.3410 - val_loss: 1.4144 - val_mean_absolute_error: 0.9152 - val_mean_squared_error: 1.4144
Epoch 15/100
237/237 [==============================] - 52s 221ms/step - loss: 1.3231 - mean_absolute_error: 0.9108 - mean_squared_error: 1.3231 - val_loss: 1.6190 - val_mean_absolute_error: 0.9362 - val_mean_squared_error: 1.6190
Epoch 16/100
237/237 [==============================] - 52s 221ms/step - loss: 1.2972 - mean_absolute_error: 0.9034 - mean_squared_error: 1.2972 - val_loss: 1.5282 - val_mean_absolute_error: 0.9141 - val_mean_squared_error: 1.5282
Epoch 17/100
237/237 [==============================] - 52s 221ms/step - loss: 1.2761 - mean_absolute_error: 0.8935 - mean_squared_error: 1.2761 - val_loss: 1.4340 - val_mean_absolute_error: 0.9389 - val_mean_squared_error: 1.4340
Epoch 18/100
237/237 [==============================] - 53s 222ms/step - loss: 1.2228 - mean_absolute_error: 0.8714 - mean_squared_error: 1.2228 - val_loss: 1.4846 - val_mean_absolute_error: 0.9145 - val_mean_squared_error: 1.4846

➡️  G1 Run 5/10
Epoch 1/100
237/237 [==============================] - 55s 223ms/step - loss: 2.2638 - mean_absolute_error: 1.2096 - mean_squared_error: 2.2638 - val_loss: 1.5759 - val_mean_absolute_error: 0.9822 - val_mean_squared_error: 1.5759
Epoch 2/100
237/237 [==============================] - 53s 222ms/step - loss: 1.8376 - mean_absolute_error: 1.1003 - mean_squared_error: 1.8376 - val_loss: 1.5570 - val_mean_absolute_error: 0.9608 - val_mean_squared_error: 1.5570
Epoch 3/100
237/237 [==============================] - 53s 221ms/step - loss: 1.7292 - mean_absolute_error: 1.0636 - mean_squared_error: 1.7292 - val_loss: 1.7002 - val_mean_absolute_error: 0.9537 - val_mean_squared_error: 1.7002
Epoch 4/100
237/237 [==============================] - 53s 222ms/step - loss: 1.6819 - mean_absolute_error: 1.0482 - mean_squared_error: 1.6819 - val_loss: 1.4740 - val_mean_absolute_error: 0.9509 - val_mean_squared_error: 1.4740
Epoch 5/100
237/237 [==============================] - 53s 222ms/step - loss: 1.6210 - mean_absolute_error: 1.0269 - mean_squared_error: 1.6210 - val_loss: 1.6656 - val_mean_absolute_error: 0.9495 - val_mean_squared_error: 1.6656
Epoch 6/100
237/237 [==============================] - 53s 225ms/step - loss: 1.5932 - mean_absolute_error: 1.0164 - mean_squared_error: 1.5932 - val_loss: 1.4473 - val_mean_absolute_error: 0.9655 - val_mean_squared_error: 1.4473
Epoch 7/100
237/237 [==============================] - 53s 222ms/step - loss: 1.5342 - mean_absolute_error: 0.9929 - mean_squared_error: 1.5342 - val_loss: 1.4364 - val_mean_absolute_error: 0.9272 - val_mean_squared_error: 1.4364
Epoch 8/100
237/237 [==============================] - 52s 221ms/step - loss: 1.5053 - mean_absolute_error: 0.9835 - mean_squared_error: 1.5053 - val_loss: 1.4430 - val_mean_absolute_error: 0.9245 - val_mean_squared_error: 1.4430
Epoch 9/100
237/237 [==============================] - 52s 221ms/step - loss: 1.4803 - mean_absolute_error: 0.9753 - mean_squared_error: 1.4803 - val_loss: 1.5085 - val_mean_absolute_error: 0.9155 - val_mean_squared_error: 1.5085
Epoch 10/100
237/237 [==============================] - 52s 221ms/step - loss: 1.4551 - mean_absolute_error: 0.9624 - mean_squared_error: 1.4551 - val_loss: 1.6616 - val_mean_absolute_error: 0.9421 - val_mean_squared_error: 1.6616
Epoch 11/100
237/237 [==============================] - 52s 221ms/step - loss: 1.4161 - mean_absolute_error: 0.9484 - mean_squared_error: 1.4161 - val_loss: 1.4483 - val_mean_absolute_error: 0.9100 - val_mean_squared_error: 1.4483
Epoch 12/100
237/237 [==============================] - 53s 222ms/step - loss: 1.3935 - mean_absolute_error: 0.9410 - mean_squared_error: 1.3935 - val_loss: 1.4091 - val_mean_absolute_error: 0.9379 - val_mean_squared_error: 1.4091
Epoch 13/100
237/237 [==============================] - 53s 223ms/step - loss: 1.3713 - mean_absolute_error: 0.9287 - mean_squared_error: 1.3713 - val_loss: 1.4666 - val_mean_absolute_error: 0.9095 - val_mean_squared_error: 1.4666
Epoch 14/100
237/237 [==============================] - 53s 222ms/step - loss: 1.3135 - mean_absolute_error: 0.9056 - mean_squared_error: 1.3135 - val_loss: 1.5293 - val_mean_absolute_error: 0.9206 - val_mean_squared_error: 1.5293
Epoch 15/100
237/237 [==============================] - 52s 221ms/step - loss: 1.3020 - mean_absolute_error: 0.9034 - mean_squared_error: 1.3020 - val_loss: 1.9007 - val_mean_absolute_error: 1.0140 - val_mean_squared_error: 1.9007
Epoch 16/100
237/237 [==============================] - 52s 221ms/step - loss: 1.2603 - mean_absolute_error: 0.8874 - mean_squared_error: 1.2603 - val_loss: 1.4290 - val_mean_absolute_error: 0.9290 - val_mean_squared_error: 1.4290
Epoch 17/100
237/237 [==============================] - 52s 222ms/step - loss: 1.2592 - mean_absolute_error: 0.8850 - mean_squared_error: 1.2592 - val_loss: 1.4191 - val_mean_absolute_error: 0.9090 - val_mean_squared_error: 1.4191

➡️  G1 Run 6/10
Epoch 1/100
237/237 [==============================] - 56s 225ms/step - loss: 2.1916 - mean_absolute_error: 1.1964 - mean_squared_error: 2.1916 - val_loss: 1.5571 - val_mean_absolute_error: 1.0276 - val_mean_squared_error: 1.5571
Epoch 2/100
237/237 [==============================] - 53s 224ms/step - loss: 1.8383 - mean_absolute_error: 1.1000 - mean_squared_error: 1.8383 - val_loss: 1.7753 - val_mean_absolute_error: 0.9844 - val_mean_squared_error: 1.7753
Epoch 3/100
237/237 [==============================] - 53s 223ms/step - loss: 1.7616 - mean_absolute_error: 1.0761 - mean_squared_error: 1.7616 - val_loss: 1.5174 - val_mean_absolute_error: 1.0179 - val_mean_squared_error: 1.5174
Epoch 4/100
237/237 [==============================] - 53s 224ms/step - loss: 1.6686 - mean_absolute_error: 1.0464 - mean_squared_error: 1.6686 - val_loss: 1.4711 - val_mean_absolute_error: 0.9499 - val_mean_squared_error: 1.4711
Epoch 5/100
237/237 [==============================] - 53s 223ms/step - loss: 1.6396 - mean_absolute_error: 1.0346 - mean_squared_error: 1.6396 - val_loss: 1.5250 - val_mean_absolute_error: 0.9335 - val_mean_squared_error: 1.5250
Epoch 6/100
237/237 [==============================] - 53s 223ms/step - loss: 1.5945 - mean_absolute_error: 1.0160 - mean_squared_error: 1.5945 - val_loss: 1.4995 - val_mean_absolute_error: 0.9285 - val_mean_squared_error: 1.4995

In [32]:
# 특정 그룹만 n번 돌리기
df_results = run_single_group_n_times(
    group_num=3,
    df_input=df_input,
    user_to_group=user_to_group,
    user_embedding_matrix=user_embedding_matrix,
    item_embedding_matrix=item_embedding_matrix,
    default_params=default_params,
    n_runs=5
)

print(df_results)

==============================
🎯 Running Group G3 for 5 runs
==============================

📊 Group G3 interactions: 85139

🔁 G3 | Run 1/5
Epoch 1/100
466/466 [==============================] - 106s 223ms/step - loss: 1.9590 - mean_absolute_error: 1.1302 - mean_squared_error: 1.9590 - val_loss: 1.5794 - val_mean_absolute_error: 0.9699 - val_mean_squared_error: 1.5794
Epoch 2/100
466/466 [==============================] - 104s 222ms/step - loss: 1.7148 - mean_absolute_error: 1.0604 - mean_squared_error: 1.7148 - val_loss: 1.5254 - val_mean_absolute_error: 0.9589 - val_mean_squared_error: 1.5254
Epoch 3/100
466/466 [==============================] - 104s 223ms/step - loss: 1.6390 - mean_absolute_error: 1.0355 - mean_squared_error: 1.6390 - val_loss: 1.4663 - val_mean_absolute_error: 0.9518 - val_mean_squared_error: 1.4663
Epoch 4/100
466/466 [==============================] - 104s 223ms/step - loss: 1.5993 - mean_absolute_error: 1.0200 - mean_squared_error: 1.5993 - val_loss: 1.4514 - val_mean_absolute_error: 0.9442 - val_mean_squared_error: 1.4514
Epoch 5/100
466/466 [==============================] - 104s 223ms/step - loss: 1.5572 - mean_absolute_error: 1.0038 - mean_squared_error: 1.5572 - val_loss: 1.6830 - val_mean_absolute_error: 0.9501 - val_mean_squared_error: 1.6830
Epoch 6/100
466/466 [==============================] - 104s 222ms/step - loss: 1.5250 - mean_absolute_error: 0.9911 - mean_squared_error: 1.5250 - val_loss: 1.4758 - val_mean_absolute_error: 0.9264 - val_mean_squared_error: 1.4758
Epoch 7/100
466/466 [==============================] - 104s 223ms/step - loss: 1.4927 - mean_absolute_error: 0.9787 - mean_squared_error: 1.4927 - val_loss: 1.5398 - val_mean_absolute_error: 0.9277 - val_mean_squared_error: 1.5398
Epoch 8/100
466/466 [==============================] - 104s 223ms/step - loss: 1.4574 - mean_absolute_error: 0.9653 - mean_squared_error: 1.4574 - val_loss: 1.4669 - val_mean_absolute_error: 0.9217 - val_mean_squared_error: 1.4669
Epoch 9/100
466/466 [==============================] - 104s 222ms/step - loss: 1.4320 - mean_absolute_error: 0.9557 - mean_squared_error: 1.4320 - val_loss: 1.5563 - val_mean_absolute_error: 0.9272 - val_mean_squared_error: 1.5563

🔁 G3 | Run 2/5
Epoch 1/100
466/466 [==============================] - 106s 223ms/step - loss: 1.9898 - mean_absolute_error: 1.1382 - mean_squared_error: 1.9898 - val_loss: 1.5171 - val_mean_absolute_error: 1.0008 - val_mean_squared_error: 1.5171
Epoch 2/100
466/466 [==============================] - 104s 222ms/step - loss: 1.7207 - mean_absolute_error: 1.0637 - mean_squared_error: 1.7207 - val_loss: 1.6662 - val_mean_absolute_error: 0.9614 - val_mean_squared_error: 1.6662
Epoch 3/100
466/466 [==============================] - 104s 224ms/step - loss: 1.6446 - mean_absolute_error: 1.0374 - mean_squared_error: 1.6446 - val_loss: 1.5628 - val_mean_absolute_error: 0.9485 - val_mean_squared_error: 1.5628
Epoch 4/100
466/466 [==============================] - 104s 223ms/step - loss: 1.6076 - mean_absolute_error: 1.0231 - mean_squared_error: 1.6076 - val_loss: 1.5009 - val_mean_absolute_error: 0.9404 - val_mean_squared_error: 1.5009
Epoch 5/100
466/466 [==============================] - 104s 223ms/step - loss: 1.5566 - mean_absolute_error: 1.0051 - mean_squared_error: 1.5566 - val_loss: 1.4213 - val_mean_absolute_error: 0.9827 - val_mean_squared_error: 1.4213
Epoch 6/100
466/466 [==============================] - 104s 223ms/step - loss: 1.5217 - mean_absolute_error: 0.9924 - mean_squared_error: 1.5217 - val_loss: 1.4073 - val_mean_absolute_error: 0.9394 - val_mean_squared_error: 1.4073
Epoch 7/100
466/466 [==============================] - 104s 223ms/step - loss: 1.4895 - mean_absolute_error: 0.9795 - mean_squared_error: 1.4895 - val_loss: 1.5767 - val_mean_absolute_error: 0.9386 - val_mean_squared_error: 1.5767
Epoch 8/100
466/466 [==============================] - 104s 223ms/step - loss: 1.4668 - mean_absolute_error: 0.9708 - mean_squared_error: 1.4668 - val_loss: 1.8464 - val_mean_absolute_error: 0.9792 - val_mean_squared_error: 1.8464
Epoch 9/100
466/466 [==============================] - 103s 220ms/step - loss: 1.4320 - mean_absolute_error: 0.9576 - mean_squared_error: 1.4320 - val_loss: 1.7083 - val_mean_absolute_error: 0.9651 - val_mean_squared_error: 1.7083
Epoch 10/100
466/466 [==============================] - 103s 220ms/step - loss: 1.4029 - mean_absolute_error: 0.9442 - mean_squared_error: 1.4029 - val_loss: 1.3968 - val_mean_absolute_error: 0.9227 - val_mean_squared_error: 1.3968
Epoch 11/100
466/466 [==============================] - 103s 221ms/step - loss: 1.3809 - mean_absolute_error: 0.9355 - mean_squared_error: 1.3809 - val_loss: 1.4953 - val_mean_absolute_error: 0.9175 - val_mean_squared_error: 1.4953
Epoch 12/100
466/466 [==============================] - 102s 220ms/step - loss: 1.3587 - mean_absolute_error: 0.9267 - mean_squared_error: 1.3587 - val_loss: 1.3889 - val_mean_absolute_error: 0.9242 - val_mean_squared_error: 1.3889
Epoch 13/100
466/466 [==============================] - 103s 220ms/step - loss: 1.3318 - mean_absolute_error: 0.9159 - mean_squared_error: 1.3318 - val_loss: 1.5593 - val_mean_absolute_error: 0.9231 - val_mean_squared_error: 1.5593
Epoch 14/100
466/466 [==============================] - 102s 218ms/step - loss: 1.3059 - mean_absolute_error: 0.9056 - mean_squared_error: 1.3059 - val_loss: 1.4205 - val_mean_absolute_error: 0.9161 - val_mean_squared_error: 1.4205
Epoch 15/100
466/466 [==============================] - 102s 220ms/step - loss: 1.2946 - mean_absolute_error: 0.8992 - mean_squared_error: 1.2946 - val_loss: 1.3990 - val_mean_absolute_error: 0.9310 - val_mean_squared_error: 1.3990
Epoch 16/100
466/466 [==============================] - 102s 219ms/step - loss: 1.2803 - mean_absolute_error: 0.8935 - mean_squared_error: 1.2803 - val_loss: 1.5936 - val_mean_absolute_error: 0.9334 - val_mean_squared_error: 1.5936
Epoch 17/100
466/466 [==============================] - 102s 218ms/step - loss: 1.2506 - mean_absolute_error: 0.8816 - mean_squared_error: 1.2506 - val_loss: 1.7214 - val_mean_absolute_error: 0.9461 - val_mean_squared_error: 1.7214

🔁 G3 | Run 3/5
Epoch 1/100
466/466 [==============================] - 105s 220ms/step - loss: 1.9743 - mean_absolute_error: 1.1318 - mean_squared_error: 1.9743 - val_loss: 1.5741 - val_mean_absolute_error: 0.9672 - val_mean_squared_error: 1.5741
Epoch 2/100
466/466 [==============================] - 102s 220ms/step - loss: 1.7108 - mean_absolute_error: 1.0600 - mean_squared_error: 1.7108 - val_loss: 1.4820 - val_mean_absolute_error: 0.9629 - val_mean_squared_error: 1.4820
Epoch 3/100
466/466 [==============================] - 102s 219ms/step - loss: 1.6469 - mean_absolute_error: 1.0374 - mean_squared_error: 1.6469 - val_loss: 1.4410 - val_mean_absolute_error: 0.9561 - val_mean_squared_error: 1.4410
Epoch 4/100
466/466 [==============================] - 102s 219ms/step - loss: 1.5954 - mean_absolute_error: 1.0197 - mean_squared_error: 1.5954 - val_loss: 1.4581 - val_mean_absolute_error: 0.9401 - val_mean_squared_error: 1.4581
Epoch 5/100
466/466 [==============================] - 102s 219ms/step - loss: 1.5420 - mean_absolute_error: 0.9989 - mean_squared_error: 1.5420 - val_loss: 1.4094 - val_mean_absolute_error: 0.9477 - val_mean_squared_error: 1.4094
Epoch 6/100
466/466 [==============================] - 102s 219ms/step - loss: 1.5121 - mean_absolute_error: 0.9887 - mean_squared_error: 1.5121 - val_loss: 1.4080 - val_mean_absolute_error: 0.9735 - val_mean_squared_error: 1.4080
Epoch 7/100
466/466 [==============================] - 102s 219ms/step - loss: 1.4777 - mean_absolute_error: 0.9748 - mean_squared_error: 1.4777 - val_loss: 1.4354 - val_mean_absolute_error: 0.9249 - val_mean_squared_error: 1.4354
Epoch 8/100
466/466 [==============================] - 102s 219ms/step - loss: 1.4590 - mean_absolute_error: 0.9673 - mean_squared_error: 1.4590 - val_loss: 1.4625 - val_mean_absolute_error: 0.9198 - val_mean_squared_error: 1.4625
Epoch 9/100
466/466 [==============================] - 102s 218ms/step - loss: 1.4401 - mean_absolute_error: 0.9597 - mean_squared_error: 1.4401 - val_loss: 1.3915 - val_mean_absolute_error: 0.9280 - val_mean_squared_error: 1.3915
Epoch 10/100
466/466 [==============================] - 102s 218ms/step - loss: 1.4062 - mean_absolute_error: 0.9473 - mean_squared_error: 1.4062 - val_loss: 1.3982 - val_mean_absolute_error: 0.9210 - val_mean_squared_error: 1.3982
Epoch 11/100
466/466 [==============================] - 102s 218ms/step - loss: 1.3803 - mean_absolute_error: 0.9348 - mean_squared_error: 1.3803 - val_loss: 1.5484 - val_mean_absolute_error: 0.9230 - val_mean_squared_error: 1.5484
Epoch 12/100
466/466 [==============================] - 102s 218ms/step - loss: 1.3587 - mean_absolute_error: 0.9258 - mean_squared_error: 1.3587 - val_loss: 1.6573 - val_mean_absolute_error: 0.9423 - val_mean_squared_error: 1.6573
Epoch 13/100
466/466 [==============================] - 102s 218ms/step - loss: 1.3361 - mean_absolute_error: 0.9172 - mean_squared_error: 1.3361 - val_loss: 1.4342 - val_mean_absolute_error: 0.9172 - val_mean_squared_error: 1.4342
Epoch 14/100
466/466 [==============================] - 102s 219ms/step - loss: 1.3160 - mean_absolute_error: 0.9085 - mean_squared_error: 1.3160 - val_loss: 1.5481 - val_mean_absolute_error: 0.9172 - val_mean_squared_error: 1.5481

🔁 G3 | Run 4/5
Epoch 1/100
466/466 [==============================] - 105s 220ms/step - loss: 2.0056 - mean_absolute_error: 1.1387 - mean_squared_error: 2.0056 - val_loss: 1.5315 - val_mean_absolute_error: 0.9828 - val_mean_squared_error: 1.5315
Epoch 2/100
466/466 [==============================] - 102s 218ms/step - loss: 1.7260 - mean_absolute_error: 1.0661 - mean_squared_error: 1.7260 - val_loss: 1.8679 - val_mean_absolute_error: 0.9892 - val_mean_squared_error: 1.8679
Epoch 3/100
466/466 [==============================] - 102s 218ms/step - loss: 1.6593 - mean_absolute_error: 1.0432 - mean_squared_error: 1.6593 - val_loss: 1.5454 - val_mean_absolute_error: 0.9486 - val_mean_squared_error: 1.5454
Epoch 4/100
466/466 [==============================] - 102s 219ms/step - loss: 1.6100 - mean_absolute_error: 1.0245 - mean_squared_error: 1.6100 - val_loss: 1.4325 - val_mean_absolute_error: 0.9599 - val_mean_squared_error: 1.4325
Epoch 5/100
466/466 [==============================] - 102s 218ms/step - loss: 1.5689 - mean_absolute_error: 1.0088 - mean_squared_error: 1.5689 - val_loss: 1.4199 - val_mean_absolute_error: 0.9485 - val_mean_squared_error: 1.4199
Epoch 6/100
466/466 [==============================] - 102s 218ms/step - loss: 1.5233 - mean_absolute_error: 0.9913 - mean_squared_error: 1.5233 - val_loss: 1.5419 - val_mean_absolute_error: 0.9352 - val_mean_squared_error: 1.5419
Epoch 7/100
466/466 [==============================] - 102s 220ms/step - loss: 1.5011 - mean_absolute_error: 0.9838 - mean_squared_error: 1.5011 - val_loss: 1.5489 - val_mean_absolute_error: 0.9308 - val_mean_squared_error: 1.5489
Epoch 8/100
466/466 [==============================] - 102s 219ms/step - loss: 1.4642 - mean_absolute_error: 0.9697 - mean_squared_error: 1.4642 - val_loss: 1.4706 - val_mean_absolute_error: 0.9239 - val_mean_squared_error: 1.4706
Epoch 9/100
466/466 [==============================] - 102s 219ms/step - loss: 1.4513 - mean_absolute_error: 0.9634 - mean_squared_error: 1.4513 - val_loss: 1.4125 - val_mean_absolute_error: 0.9268 - val_mean_squared_error: 1.4125
Epoch 10/100
466/466 [==============================] - 103s 221ms/step - loss: 1.4106 - mean_absolute_error: 0.9478 - mean_squared_error: 1.4106 - val_loss: 1.6705 - val_mean_absolute_error: 0.9437 - val_mean_squared_error: 1.6705
Epoch 11/100
466/466 [==============================] - 102s 219ms/step - loss: 1.3932 - mean_absolute_error: 0.9391 - mean_squared_error: 1.3932 - val_loss: 1.5337 - val_mean_absolute_error: 0.9214 - val_mean_squared_error: 1.5337
Epoch 12/100
466/466 [==============================] - 102s 219ms/step - loss: 1.3719 - mean_absolute_error: 0.9326 - mean_squared_error: 1.3719 - val_loss: 1.6500 - val_mean_absolute_error: 0.9391 - val_mean_squared_error: 1.6500
Epoch 13/100
466/466 [==============================] - 102s 219ms/step - loss: 1.3464 - mean_absolute_error: 0.9216 - mean_squared_error: 1.3464 - val_loss: 1.5475 - val_mean_absolute_error: 0.9231 - val_mean_squared_error: 1.5475
Epoch 14/100
466/466 [==============================] - 102s 218ms/step - loss: 1.3233 - mean_absolute_error: 0.9109 - mean_squared_error: 1.3233 - val_loss: 1.4980 - val_mean_absolute_error: 0.9207 - val_mean_squared_error: 1.4980

🔁 G3 | Run 5/5
Epoch 1/100
466/466 [==============================] - 104s 219ms/step - loss: 1.9874 - mean_absolute_error: 1.1383 - mean_squared_error: 1.9874 - val_loss: 1.5702 - val_mean_absolute_error: 0.9742 - val_mean_squared_error: 1.5702
Epoch 2/100
466/466 [==============================] - 102s 218ms/step - loss: 1.7178 - mean_absolute_error: 1.0626 - mean_squared_error: 1.7178 - val_loss: 1.4926 - val_mean_absolute_error: 0.9679 - val_mean_squared_error: 1.4926
Epoch 3/100
466/466 [==============================] - 102s 219ms/step - loss: 1.6430 - mean_absolute_error: 1.0373 - mean_squared_error: 1.6430 - val_loss: 1.6065 - val_mean_absolute_error: 0.9503 - val_mean_squared_error: 1.6065
Epoch 4/100
466/466 [==============================] - 102s 219ms/step - loss: 1.5935 - mean_absolute_error: 1.0180 - mean_squared_error: 1.5935 - val_loss: 1.8200 - val_mean_absolute_error: 0.9861 - val_mean_squared_error: 1.8200
Epoch 5/100
466/466 [==============================] - 102s 219ms/step - loss: 1.5498 - mean_absolute_error: 1.0032 - mean_squared_error: 1.5498 - val_loss: 1.4809 - val_mean_absolute_error: 0.9351 - val_mean_squared_error: 1.4809
Epoch 6/100
466/466 [==============================] - 102s 219ms/step - loss: 1.5194 - mean_absolute_error: 0.9924 - mean_squared_error: 1.5194 - val_loss: 1.4650 - val_mean_absolute_error: 0.9315 - val_mean_squared_error: 1.4650
Epoch 7/100
466/466 [==============================] - 102s 218ms/step - loss: 1.4801 - mean_absolute_error: 0.9771 - mean_squared_error: 1.4801 - val_loss: 1.5105 - val_mean_absolute_error: 0.9295 - val_mean_squared_error: 1.5105
Epoch 8/100
466/466 [==============================] - 102s 218ms/step - loss: 1.4601 - mean_absolute_error: 0.9687 - mean_squared_error: 1.4601 - val_loss: 1.4323 - val_mean_absolute_error: 0.9285 - val_mean_squared_error: 1.4323
Epoch 9/100
466/466 [==============================] - 102s 219ms/step - loss: 1.4277 - mean_absolute_error: 0.9553 - mean_squared_error: 1.4277 - val_loss: 1.5566 - val_mean_absolute_error: 0.9305 - val_mean_squared_error: 1.5566
Epoch 10/100
466/466 [==============================] - 102s 218ms/step - loss: 1.4053 - mean_absolute_error: 0.9465 - mean_squared_error: 1.4053 - val_loss: 1.3980 - val_mean_absolute_error: 0.9361 - val_mean_squared_error: 1.3980
Epoch 11/100
466/466 [==============================] - 102s 218ms/step - loss: 1.3828 - mean_absolute_error: 0.9373 - mean_squared_error: 1.3828 - val_loss: 1.4305 - val_mean_absolute_error: 0.9183 - val_mean_squared_error: 1.4305
Epoch 12/100
466/466 [==============================] - 102s 219ms/step - loss: 1.3689 - mean_absolute_error: 0.9300 - mean_squared_error: 1.3689 - val_loss: 1.4129 - val_mean_absolute_error: 0.9298 - val_mean_squared_error: 1.4129
Epoch 13/100
466/466 [==============================] - 102s 218ms/step - loss: 1.3346 - mean_absolute_error: 0.9170 - mean_squared_error: 1.3346 - val_loss: 1.4630 - val_mean_absolute_error: 0.9165 - val_mean_squared_error: 1.4630
Epoch 14/100
466/466 [==============================] - 102s 218ms/step - loss: 1.3183 - mean_absolute_error: 0.9101 - mean_squared_error: 1.3183 - val_loss: 1.4050 - val_mean_absolute_error: 0.9391 - val_mean_squared_error: 1.4050
Epoch 15/100
466/466 [==============================] - 102s 218ms/step - loss: 1.2991 - mean_absolute_error: 0.9024 - mean_squared_error: 1.2991 - val_loss: 1.5122 - val_mean_absolute_error: 0.9128 - val_mean_squared_error: 1.5122
        MAE       MSE      RMSE       MAPE  group  run
0  0.943044  1.456348  1.206793  43.690055      3    1
1  0.917518  1.381737  1.175473  40.413987      3    2
2  0.924501  1.395267  1.181214  41.515295      3    3
3  0.923321  1.412591  1.188525  42.993843      3    4
4  0.932108  1.397085  1.181983  40.488067      3    5

In [33]:
timestamp = datetime.now().strftime("%Y%m%d_%H%M")

df_results.to_csv(f"results_{CATEGORY}_{timestamp}.csv", index=False, encoding="utf-8-sig")

In [ ]:
save_results_to_csv(df_results, prefix=f"g1_g4_{CATEGORY}")

📁 Saved: g1_g4_yelp_20251217_1540.csv

'g1_g4_yelp_20251217_1540.csv'